# 3 Stages to run through
stages:
  - Build
  - Test
  - Deploy

# Uses the node docker image for JS applications
image: node:alpine

#Changes directory from home to the code directory
before_script:
  - cd code/dungeons-and-dragons-app
  - yarn install

# Perform the 3 stages
build:
  stage: Build
  tags:
    - shell
  script:
    - echo "Building stage 1/1"
  allow_failure: false

# Boosts performance
cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ~/.npm

unit_testing:
  stage: Test
  tags:
    - shell
  script:
    - echo "Testing stage 1/1"
    - yarn add jest-expo
    - npx jest --ci
  allow_failure: false

deploy:
  stage: Deploy
  tags:
    - shell
  script:
    - echo "Deployment stage 1/1"
    - yarn global add firebase-tools
    - echo "Building application"
    - yarn build
    - echo "Deploying"
    - firebase use --token $FIREBASE_TOKEN
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN --only functions,hosting
  only:
    refs:
      - master
    changes:
      - code/dungeons-and-dragons-app/**/*
  allow_failure: true