stages:
  - Build
  - Test
  - Deploy

image: gradle:alpine

build_a:
  stage: Build
  tags:
    - shell
  script:
    - echo "Building stage 1/2"
  allow_failure: false

build_b:
  stage: Build
  tags:
    - shell
  script:
    - echo "Building stage 2/2"
  allow_failure: false

unit_testing:
  image: node:alpine
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ~/.npm
stages:
  - test
before_script:
  - npm ci
jest-tests:
  stage: test
  script:
    - echo "Testing stage 1/1"
    - npx jest --ci

deploy_a:
  stage: Deploy
  tags:
    - shell
  script:
    - echo "Deployment stage 1/2"
  allow_failure: true

deploy_b:
  stage: Deploy
  tags:
    - shell
  script:
    - echo "Deployment stage 2/2"
  allow_failure: true
