stages:
  - Build
  - Test
  - Deploy

image: node:alpine

before_script:
  - cd code/dungeons-and-dragons-app
  - yarn add --dev jest babel-jest @babel/preset-env @babel/preset-react react-test-renderer

build_a:
  stage: Build
  tags:
    - shell
  script:
    - echo "Building stage 1/2"
  allow_failure: false

build_b:
  stage: Build
  tags:
    - shell
  script:
    - echo "Building stage 2/2"
  allow_failure: false

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ~/.npm

unit_testing:
  stage: Test
  script:
    - echo "Testing stage 1/1"
    - npx jest --ci
  allow_failure: false

deploy_a:
  stage: Deploy
  tags:
    - shell
  script:
    - echo "Deployment stage 1/2"
  allow_failure: true

deploy_b:
  stage: Deploy
  tags:
    - shell
  script:
    - echo "Deployment stage 2/2"
  allow_failure: true
